"""Core orchestration: stream → filter → (early-return-if-empty) → fetch → rank → QA.

Implements the Phase 3 vertical slice described in ``plan.md``. The function
:func:`run` is the single entry point the API handler calls; it takes only
Protocol-level dependencies (``Ports``) and configuration, so it is testable
without any HTTP or process-pool infrastructure.

See ``architect.md`` section 4 (stream handling), section 6 (concurrency),
and section 8 (partial-failure policy) for the contract this implements.
"""

from __future__ import annotations

import asyncio
import time
from typing import TYPE_CHECKING

from app.api.schemas import EnrichedQAResponse, Meta
from app.core.errors import PartialFailureThresholdExceededError, StorageFetchError
from app.core.models import ScreenshotWithBytes

if TYPE_CHECKING:
    from uuid import UUID

    from app.api.schemas import EnrichedQARequest
    from app.config import Settings
    from app.core.models import ScreenshotRef
    from app.deps import Ports


async def run(
    req: EnrichedQARequest,
    ports: Ports,
    config: Settings,
    request_id: str,
) -> EnrichedQAResponse:
    """Execute the enriched QA pipeline for one request.

    Pipeline steps:

    1. Stream the project's screenshots and filter to ``[req.from_, req.to)``.
    2. If no refs remain after filtering, return a 200 with ``answer=""`` and
       zero counts. Fetch, rank, and QA are skipped entirely.
    3. Fetch image bytes with per-request bounded concurrency. Each
       :class:`~app.core.errors.StorageFetchError` is caught and counted.
    4. If ``failed / total > config.max_fetch_failure_ratio`` (only when
       ``total > 0``), raise :class:`~app.core.errors.PartialFailureThresholdExceededError`.
    5. Rank up to ``config.max_relevant_images`` most relevant ids.
    6. Call :meth:`WorkflowServicesClient.qa_answer` with the ranker order
       preserved.
    7. Return :class:`EnrichedQAResponse` including timing and counters.

    Args:
        req: Validated request body.
        ports: Protocol-dependency bundle (workflow, storage, relevance).
        config: Runtime configuration.
        request_id: Correlation id generated by the HTTP handler.

    Returns:
        :class:`EnrichedQAResponse` with the answer and per-request metadata.

    Raises:
        PartialFailureThresholdExceededError: When too many storage fetches
            fail within a single request.
        WorkflowUpstreamError: Propagated unchanged from the Workflow adapter.
    """
    latency: dict[str, int] = {}
    t0 = time.perf_counter()

    # 1. Stream + filter
    stream_start = time.perf_counter()
    refs = await _stream_and_filter(
        ports,
        req.project_id,
        from_=req.from_,
        to=req.to,
        assume_sorted=config.assume_sorted_stream,
    )
    latency["stream"] = _elapsed_ms(stream_start)

    images_considered = len(refs)

    # 2. Empty-window short-circuit
    if images_considered == 0:
        latency["total"] = _elapsed_ms(t0)
        return EnrichedQAResponse(
            answer="",
            meta=Meta(
                request_id=request_id,
                images_considered=0,
                images_relevant=0,
                errors={},
                latency_ms=latency,
            ),
        )

    # 3. Fetch with bounded concurrency + partial-failure counting
    fetch_start = time.perf_counter()
    images, failed = await _fetch_all(ports, refs, max_concurrent=config.max_concurrent_fetches)
    latency["fetch"] = _elapsed_ms(fetch_start)

    # 4. Partial-failure threshold (total > 0 here by construction)
    total_fetches = len(refs)
    if failed / total_fetches > config.max_fetch_failure_ratio:
        raise PartialFailureThresholdExceededError(failed=failed, total=total_fetches)

    errors: dict[str, int] = {}
    if failed > 0:
        errors["storage_fetch_failed"] = failed

    # 5. Rank
    rank_start = time.perf_counter()
    relevant_ids = await ports.relevance.rank(images, req.question, config.max_relevant_images)
    latency["rank"] = _elapsed_ms(rank_start)

    # 6. QA
    qa_start = time.perf_counter()
    answer = await ports.workflow.qa_answer(req.question, relevant_ids)
    latency["qa"] = _elapsed_ms(qa_start)

    latency["total"] = _elapsed_ms(t0)
    return EnrichedQAResponse(
        answer=answer,
        meta=Meta(
            request_id=request_id,
            images_considered=images_considered,
            images_relevant=len(relevant_ids),
            errors=errors,
            latency_ms=latency,
        ),
    )


async def _stream_and_filter(
    ports: Ports,
    project_id: UUID,
    *,
    from_: int,
    to: int,
    assume_sorted: bool,
) -> list[ScreenshotRef]:
    """Consume the workflow stream, keep refs inside ``[from_, to)``.

    When ``assume_sorted`` is True, stop reading as soon as a timestamp at
    or past ``to`` is seen - this bounds work for the common sorted case.
    When False, drain to EOF and drop out-of-window rows one by one.

    Args:
        ports: Port bundle - only ``workflow`` is used.
        project_id: Project UUID passed to ``stream_project``.
        from_: Inclusive window lower bound.
        to: Exclusive window upper bound.
        assume_sorted: Whether to short-circuit on the first past-window row.

    Returns:
        Refs inside the window, in the order the stream yielded them.
    """
    refs: list[ScreenshotRef] = []
    async for ref in ports.workflow.stream_project(project_id):
        if ref.timestamp < from_:
            continue
        if ref.timestamp >= to:
            if assume_sorted:
                break
            continue
        refs.append(ref)
    return refs


async def _fetch_all(
    ports: Ports,
    refs: list[ScreenshotRef],
    *,
    max_concurrent: int,
) -> tuple[list[ScreenshotWithBytes], int]:
    """Fetch image bytes for every ``ref`` with bounded concurrency.

    Each :class:`~app.core.errors.StorageFetchError` is swallowed and counted;
    the orchestrator decides whether that count crosses the threshold. Other
    exceptions propagate immediately - they indicate a programming error or
    an unexpected transport-layer failure that shouldn't be hidden.

    Args:
        ports: Port bundle - only ``storage`` is used.
        refs: Refs to fetch, in iteration order.
        max_concurrent: Per-request semaphore size.

    Returns:
        A tuple ``(successes, failed_count)`` where ``successes`` is a list
        of :class:`ScreenshotWithBytes` preserving the input order (minus
        failures).
    """
    sem = asyncio.Semaphore(max_concurrent)
    results: list[ScreenshotWithBytes | None] = [None] * len(refs)
    failed = 0

    async def fetch_one(idx: int, ref: ScreenshotRef) -> None:
        nonlocal failed
        async with sem:
            try:
                data = await ports.storage.get_image(ref.image_id)
            except StorageFetchError:
                # asyncio single-threaded: read-modify-write on `failed`
                # between two `await`-free lines is preemption-safe.
                failed += 1
                return
        results[idx] = ScreenshotWithBytes(ref=ref, data=data)

    await asyncio.gather(*(fetch_one(i, r) for i, r in enumerate(refs)))
    return [r for r in results if r is not None], failed


def _elapsed_ms(start: float) -> int:
    """Return elapsed milliseconds since ``start`` (from :func:`time.perf_counter`)."""
    return max(int((time.perf_counter() - start) * 1000), 0)
