"""Core orchestration: stream → filter → (early-return-if-empty) → fetch → rank → QA.

Implements the Phase 3 vertical slice described in ``plan.md``. The function
:func:`run` is the single entry point the API handler calls; it takes only
Protocol-level dependencies (``Ports``) and configuration, so it is testable
without any HTTP or process-pool infrastructure.

See ``architect.md`` section 4 (stream handling), section 6 (concurrency),
and section 8 (partial-failure policy) for the contract this implements.
"""

from __future__ import annotations

import asyncio
import time
from typing import TYPE_CHECKING

import structlog
from opentelemetry import trace

from app.api.schemas import EnrichedQAResponse, Meta
from app.core.errors import PartialFailureThresholdExceededError, StorageFetchError
from app.core.models import ScreenshotWithBytes

if TYPE_CHECKING:
    from uuid import UUID

    from app.api.schemas import EnrichedQARequest
    from app.config import Settings
    from app.core.models import ScreenshotRef
    from app.deps import Ports


_tracer = trace.get_tracer(__name__)
_log = structlog.get_logger(__name__)


async def run(
    req: EnrichedQARequest,
    ports: Ports,
    config: Settings,
    request_id: str,
) -> EnrichedQAResponse:
    """Execute the enriched QA pipeline for one request.

    Pipeline steps:

    1. Stream the project's screenshots and filter to ``[req.from_, req.to)``.
    2. If no refs remain after filtering, return a 200 with ``answer=""`` and
       zero counts. Fetch, rank, and QA are skipped entirely.
    3. **Pre-fetch sampling.** If the filtered ref list exceeds
       ``config.max_rank_input``, downsample uniformly over the
       ``[from_, to)`` window. This keeps timestamps intact and avoids
       fetching images that would be discarded anyway. ``images_considered``
       in the response reflects the pre-sampling count - the filtered
       set the service genuinely saw.
    4. Fetch image bytes with per-request bounded concurrency. Each
       :class:`~app.core.errors.StorageFetchError` is caught and counted.
    5. If ``failed / total > config.max_fetch_failure_ratio`` (only when
       ``total > 0``), raise :class:`~app.core.errors.PartialFailureThresholdExceededError`.
    6. Rank up to ``config.max_relevant_images`` most relevant ids.
    7. Call :meth:`WorkflowServicesClient.qa_answer` with the ranker order
       preserved.
    8. Return :class:`EnrichedQAResponse` including timing and counters.

    Args:
        req: Validated request body.
        ports: Protocol-dependency bundle (workflow, storage, relevance).
        config: Runtime configuration.
        request_id: Correlation id generated by the HTTP handler.

    Returns:
        :class:`EnrichedQAResponse` with the answer and per-request metadata.

    Raises:
        PartialFailureThresholdExceededError: When too many storage fetches
            fail within a single request.
        WorkflowUpstreamError: Propagated unchanged from the Workflow adapter.
    """
    latency: dict[str, int] = {}
    t0 = time.perf_counter()
    # Initialise here so the except block always has sensible values even if
    # an exception fires before the corresponding pipeline stage completes.
    images_considered = 0
    failed = 0
    relevant_ids: list[str] = []

    with _tracer.start_as_current_span("enriched_qa.handler") as handler_span:
        handler_span.set_attribute("project_id", str(req.project_id))
        handler_span.set_attribute("time_window.from", req.from_)
        handler_span.set_attribute("time_window.to", req.to)
        handler_span.set_attribute("question.length", len(req.question))
        # Defaults so dashboards keying off the request span always find these
        # attributes, even when an exception fires before the stage that would
        # normally set the real value.
        handler_span.set_attribute("images_considered", 0)
        handler_span.set_attribute("images_relevant", 0)
        handler_span.set_attribute("fetches.failed", 0)

        _log.info(
            "enriched_qa.start",
            project_id=str(req.project_id),
            time_window_from=req.from_,
            time_window_to=req.to,
            question_length=len(req.question),
        )

        try:
            # 1. Stream + filter
            stream_start = time.perf_counter()
            with _tracer.start_as_current_span("workflow.stream") as stream_span:
                stream_span.set_attribute("project_id", str(req.project_id))
                refs = await _stream_and_filter(
                    ports,
                    req.project_id,
                    from_=req.from_,
                    to=req.to,
                    assume_sorted=config.assume_sorted_stream,
                )
                stream_span.set_attribute("refs.in_window", len(refs))
            latency["stream"] = _elapsed_ms(stream_start)

            images_considered = len(refs)
            handler_span.set_attribute("images_considered", images_considered)

            # 2. Empty-window short-circuit
            if images_considered == 0:
                latency["total"] = _elapsed_ms(t0)
                _log.info(
                    "enriched_qa.empty_window",
                    project_id=str(req.project_id),
                    latency_ms=latency,
                )
                return EnrichedQAResponse(
                    answer="",
                    meta=Meta(
                        request_id=request_id,
                        images_considered=0,
                        images_relevant=0,
                        errors={},
                        latency_ms=latency,
                    ),
                )

            # 3. Pre-fetch sampling: cap work at MAX_RANK_INPUT by sampling over
            # the request window. We sample `ScreenshotRef` values (not bytes)
            # so timestamps survive and we never fetch images we'd discard.
            refs_to_fetch = _sample_uniform_over_window(
                refs,
                from_=req.from_,
                to=req.to,
                max_input=config.max_rank_input,
            )

            # 4. Fetch with bounded concurrency + partial-failure counting
            fetch_start = time.perf_counter()
            with _tracer.start_as_current_span("storage.fetch_batch") as fetch_span:
                fetch_span.set_attribute("refs.requested", len(refs_to_fetch))
                fetch_span.set_attribute("max_concurrent", config.max_concurrent_fetches)
                images, failed = await _fetch_all(
                    ports, refs_to_fetch, max_concurrent=config.max_concurrent_fetches
                )
                fetch_span.set_attribute("fetches.succeeded", len(images))
                fetch_span.set_attribute("fetches.failed", failed)
            latency["fetch"] = _elapsed_ms(fetch_start)
            # Update eagerly so the handler span carries the real value even if
            # the partial-failure threshold check raises below.
            handler_span.set_attribute("fetches.failed", failed)

            # 5. Partial-failure threshold (total > 0 here by construction)
            total_fetches = len(refs_to_fetch)
            if failed / total_fetches > config.max_fetch_failure_ratio:
                raise PartialFailureThresholdExceededError(failed=failed, total=total_fetches)

            errors: dict[str, int] = {}
            if failed > 0:
                errors["storage_fetch_failed"] = failed

            # 6. Rank
            rank_start = time.perf_counter()
            with _tracer.start_as_current_span("relevance.rank") as rank_span:
                rank_span.set_attribute("rank.input_size", len(images))
                rank_span.set_attribute("rank.top_k", config.max_relevant_images)
                relevant_ids = await ports.relevance.rank(
                    images, req.question, config.max_relevant_images
                )
                rank_span.set_attribute("rank.output_size", len(relevant_ids))
            latency["rank"] = _elapsed_ms(rank_start)
            # Update eagerly so a QA-layer exception still leaves a ranked count.
            handler_span.set_attribute("images_relevant", len(relevant_ids))

            # 7. QA
            qa_start = time.perf_counter()
            with _tracer.start_as_current_span("workflow.qa_answer") as qa_span:
                qa_span.set_attribute("qa.relevant_count", len(relevant_ids))
                answer = await ports.workflow.qa_answer(req.question, relevant_ids)
                qa_span.set_attribute("qa.answer_length", len(answer))
            latency["qa"] = _elapsed_ms(qa_start)

            latency["total"] = _elapsed_ms(t0)
            _log.info(
                "enriched_qa.done",
                project_id=str(req.project_id),
                images_considered=images_considered,
                images_relevant=len(relevant_ids),
                fetches_failed=failed,
                latency_ms=latency,
            )

            return EnrichedQAResponse(
                answer=answer,
                meta=Meta(
                    request_id=request_id,
                    images_considered=images_considered,
                    images_relevant=len(relevant_ids),
                    errors=errors,
                    latency_ms=latency,
                ),
            )

        except Exception:
            latency.setdefault("total", _elapsed_ms(t0))
            _log.error(
                "enriched_qa.failed",
                project_id=str(req.project_id),
                images_considered=images_considered,
                fetches_failed=failed,
                latency_ms=latency,
                exc_info=True,
            )
            raise


async def _stream_and_filter(
    ports: Ports,
    project_id: UUID,
    *,
    from_: int,
    to: int,
    assume_sorted: bool,
) -> list[ScreenshotRef]:
    """Consume the workflow stream, keep refs inside ``[from_, to)``.

    When ``assume_sorted`` is True, stop reading as soon as a timestamp at
    or past ``to`` is seen - this bounds work for the common sorted case.
    When False, drain to EOF and drop out-of-window rows one by one.

    Args:
        ports: Port bundle - only ``workflow`` is used.
        project_id: Project UUID passed to ``stream_project``.
        from_: Inclusive window lower bound.
        to: Exclusive window upper bound.
        assume_sorted: Whether to short-circuit on the first past-window row.

    Returns:
        Refs inside the window, in the order the stream yielded them.
    """
    refs: list[ScreenshotRef] = []
    async for ref in ports.workflow.stream_project(project_id):
        if ref.timestamp < from_:
            continue
        if ref.timestamp >= to:
            if assume_sorted:
                break
            continue
        refs.append(ref)
    return refs


async def _fetch_all(
    ports: Ports,
    refs: list[ScreenshotRef],
    *,
    max_concurrent: int,
) -> tuple[list[ScreenshotWithBytes], int]:
    """Fetch image bytes for every ``ref`` with bounded concurrency.

    Each :class:`~app.core.errors.StorageFetchError` is swallowed and counted;
    the orchestrator decides whether that count crosses the threshold. Other
    exceptions propagate immediately - they indicate a programming error or
    an unexpected transport-layer failure that shouldn't be hidden.

    Args:
        ports: Port bundle - only ``storage`` is used.
        refs: Refs to fetch, in iteration order.
        max_concurrent: Per-request semaphore size.

    Returns:
        A tuple ``(successes, failed_count)`` where ``successes`` is a list
        of :class:`ScreenshotWithBytes` preserving the input order (minus
        failures).
    """
    sem = asyncio.Semaphore(max_concurrent)
    results: list[ScreenshotWithBytes | None] = [None] * len(refs)
    failed = 0

    async def fetch_one(idx: int, ref: ScreenshotRef) -> None:
        nonlocal failed
        async with sem:
            try:
                data = await ports.storage.get_image(ref.image_id)
            except StorageFetchError:
                # asyncio single-threaded: read-modify-write on `failed`
                # between two `await`-free lines is preemption-safe.
                failed += 1
                return
        results[idx] = ScreenshotWithBytes(ref=ref, data=data)

    await asyncio.gather(*(fetch_one(i, r) for i, r in enumerate(refs)))
    return [r for r in results if r is not None], failed


def _elapsed_ms(start: float) -> int:
    """Return elapsed milliseconds since ``start`` (from :func:`time.perf_counter`)."""
    return max(int((time.perf_counter() - start) * 1000), 0)


def _sample_uniform_over_window(
    refs: list[ScreenshotRef],
    *,
    from_: int,
    to: int,
    max_input: int,
) -> list[ScreenshotRef]:
    """Downsample ``refs`` over the ``[from_, to)`` window with two passes.

    Pass 1 picks the first ref seen in each of ``max_input`` equal-width
    time buckets. This guarantees temporal spread: no part of the window
    is silently dropped when refs cluster elsewhere.

    Pass 2 fills any remaining slots (up to ``max_input``) from the refs
    that were skipped by pass 1, preserving their stream order. Without
    this pass, a dense burst in a single bucket would collapse to one
    ref even when the budget allows more.

    Pass 1 alone is temporally clean but wasteful; pass 2 alone is
    dense-first and loses spread. Running both uses the full budget
    while still front-loading representation.

    Args:
        refs: Filtered refs from the stream. May be empty.
        from_: Window lower bound (inclusive). Must be less than ``to``.
        to: Window upper bound (exclusive).
        max_input: Maximum allowed size of the returned list. Must be > 0.

    Returns:
        A list of at most ``max_input`` refs in stream order. Returned
        unchanged when already at or below the cap. When ``len(refs) >
        max_input`` the output length equals ``max_input`` (pass 2
        always has enough leftovers to fill).
    """
    if len(refs) <= max_input:
        return refs
    # Caller (orchestrator) has already validated the window is non-empty
    # and that this path is only reached when refs > 0.
    bucket_width = (to - from_) / max_input
    selected: list[ScreenshotRef] = []
    leftovers: list[ScreenshotRef] = []
    seen_buckets: set[int] = set()
    for ref in refs:
        idx = int((ref.timestamp - from_) / bucket_width)
        # Clamp the last bucket: timestamp == to-1 (nearly at edge) may
        # round to `max_input`. Clip to the last bucket to avoid a stray
        # key that'd make the first pass exceed max_input via rounding.
        if idx >= max_input:
            idx = max_input - 1
        if idx not in seen_buckets:
            seen_buckets.add(idx)
            selected.append(ref)
        else:
            leftovers.append(ref)
    # Pass 2: fill remaining slots from leftovers in stream order.
    remaining = max_input - len(selected)
    if remaining > 0:
        selected.extend(leftovers[:remaining])
    return selected
